### ISSUE TITLE
Crash if application makes outbound requests

### ISSUE THREAD

**Issue by sjanuary** [RuntimeTools/appmetrics-zipkin#35]
I started testing for the 1.1.1 release but my simple application was crashing.  It doesn't crash without appmetrics-zipkin.

```js
require('appmetrics-zipkin')({
  host: 'localhost',
  port: 9411,
  serviceName:'frontend',
  sampleRate: 1.0
});

var http = require('http');

const port = 3000;

const requestHandler = (request, response) => {  
  response.end('Hello')
}

const server = http.createServer(requestHandler);

server.listen(port, (err) => {  
  if (err) {
    return console.log('An error occurred', err)
  }
  console.log(`Server is listening on ${port}`)
});

setInterval(function() {http.get('http://localhost:3000/')}, 3000);
```

Error was:
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:80
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
```

**Comment by Eli-Goldberg** [comment]
Still haven't figured out exactly what's going on, but it works if you replace the call with: 

`http.get({ hostname: 'localhost',port: 3000 })`

**Comment by Eli-Goldberg** [comment]
This is the cause:
https://github.com/RuntimeTools/appmetrics-zipkin/blob/master/probes/http-outbound-probe-zipkin.js#L82

I think I could get a fix, would take a day though

**Comment by Eli-Goldberg** [comment]
I've added a test for that in #37
